# create these secrets in your repository settings
# SSH_PRIVATE_KEY 
# REMOTE_HOST 
# REMOTE_USER 
name: Build & deploy ASP.NET Core API
run-name: Build & deploy ASP.NET Core API
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x       
      - name: Download cache 
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Install dependencies
        run: dotnet restore --locked-mode
      - name: Publish 
        run: dotnet publish WebAPI -c Release -o bin/WebAPI -r linux-arm64 --no-restore --self-contained 
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "bin/WebAPI/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/WebAPI