# create these secrets in your repository settings
# SSH_PRIVATE_KEY 
# REMOTE_HOST 
# REMOTE_USER 
name: Build & deploy ASP.NET Core MVC
run-name: Build & deploy ASP.NET Core MVC
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x       
      - name: Download cache 
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Install dependencies
        run: dotnet restore --locked-mode
      - name: Publish 
        run: dotnet publish WebMVC -c Release -o bin/WebMVC -r linux-arm64 --no-restore --self-contained
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "bin/WebMVC/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/MapSqlWebMVC
      - name: Execute update command on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /home/${{ secrets.REMOTE_USER }}/mapsql.sh
