# create these secrets in your repository settings
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
# DOCKERHUB_REPOSITORY_UPDATE
# MYSQL_HOST
# MYSQL_PORT
# MYSQL_USERNAME
# MYSQL_PASSWORD

name: Release Docker build
run-name: Release Docker build
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
        
      - name: Publish 
        run: dotnet publish ConsoleUpdate -c Release -p:PublishSingleFile=true -o bin/ConsoleUpdate
      
      - name: 
        uses: im-open/variable-substitution@v2.0.5
          files: 'bin/ConsoleUpdate/appsettings.Production.json'
          env:
            ConnectionStrings.DataSource: 'Host=${{ secrets.MYSQL_HOST }};Port=${{ secrets.MYSQL_PORT }};Username=${{ secrets.MYSQL_USERNAME }};Password=${{ secrets.MYSQL_PASSWORD }}'

      - name: Build and push update image
        uses: docker/build-push-action@v4
        with:
          file: ./ConsoleUpdate/Dockerfile
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_UPDATE }}:latest 
     
